### update an exists patient entity
PUT http://localhost:4000/patients/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json

{
  "name": "john Doe",
  "email": "test2@example.com",
  "address": "19/2 main street",
  "dateOfBirth": "1999-01-02"
}

###